# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField()),
                ('fecha_entrega', models.DateField()),
                ('genero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pelicula.Genero')),
                ('pelicula', models.ManyToManyField(to='Pelicula.Pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
