# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=10, verbose_name='Clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=150, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('sinopsis', models.CharField(max_length=350, verbose_name='Sinopsis')),
                ('duracion', models.CharField(max_length=50, verbose_name='Duracion')),
                ('esteno', models.BooleanField()),
                ('actores', models.ManyToManyField(to='Pelicula.Actores')),
                ('clasificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pelicula.Clas')),
                ('genero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pelicula.Genero')),
            ],
        ),
    ]
