# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pelicula', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='esteno',
            new_name='estreno',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='rentada',
            field=models.BooleanField(default=False),
        ),
    ]
